# Generated by Django 4.0.5 on 2023-09-12 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Filterlog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=150)),
                ('severity', models.CharField(max_length=50)),
                ('facility', models.CharField(max_length=50)),
                ('application', models.CharField(max_length=70)),
                ('message', models.TextField()),
                ('timestamp', models.DateTimeField()),
                ('role', models.CharField(max_length=350)),
                ('is_know', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Hostnames',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=150)),
                ('ipaddress', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('role_severity', models.CharField(max_length=50)),
            ],
        ),
    ]
